---
title: "college_final_project"
format: html
execute:
  http: true
---

```{r}
# install.packages("httr2")
library(httr2)
library(tidyverse)
```

```{r}
school_list <- list()

for (k in 1:500) {
college_request <- request("https://api.data.gov") %>% 
  req_url_path_append("ed") %>% 
  req_url_path_append("collegescorecard") %>% 
  req_url_path_append("v1") %>% 
  req_url_path_append("schools") %>% 
  req_url_query(
    api_key = "sXz5twfrusSSiWtD5EQ35d4e3XNzfiw3m4yHiMuv",
    fields = "id,school.name,latest.student.size,school.state,latest.cost.tuition.in_state,latest.cost.tuition.out_of_state" ,
    per_page = 100,
    page = k,
  )


  college_response <- req_perform(college_request)
  data <- college_response %>% resp_body_json(simplifyVector = TRUE)
  results <- data$results
  school_list[[k]] <- results
  
  if (nrow(results) < 100) {
    break
  }
}
# install.packages("janitor")

# college_tbl <- college_response %>%
  # resp_body_json(simplifyVector = TRUE) %>%
  # pluck("results") %>%
  # as_tibble()

# college_tbl
```

```{r}
colleges <- bind_rows(school_list)
```
```{r}
colnames(colleges)
```

```{r}

# not sure how accurate the apps & accept columns
# could use this set too it has more rows:
# https://www.kaggle.com/datasets/thedevastator/u-s-department-of-education-college-scorecard-da
#college2 <- read_csv("College_Data.csv")
#college2

#college2 <- college2 %>%
# rename(name = ...1)

#colleges <- colleges %>%
#  rename(name = school.name)
```

```{r}
# merged_colleges <- left_join(college2, colleges, by = "name")

# some duplicates in here
```

```{r}
alt_colleges <- read_csv("alt_college_data.csv")
```

```{r}
alt_colleges <- alt_colleges %>%
  rename(name = INSTNM)
```

```{r}
merged_colleges_big <- left_join(colleges, alt_colleges, by = c("school.name" = "name"))
```


```{r}
merged_colleges %>%
  ggplot(aes(x = Private, y = latest.cost.tuition.out_of_state)) +
    geom_boxplot() +
    coord_flip() +
    theme_minimal() +
    labs(
      y = "Tuition (Out of State)",
      x = "Private",
      title = "Cost of Public vs. Private Schools"
    )
```
